# db, phpMyAdmin et... are containers

services:
    db:                                             # container
        image: mysql                                # image
        container_name: db_yd_docker_symfony
        restart: always
        volumes:                                    # data persitance 
            - db-data:/var/lib/mysql
        environment: 
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:                                   # network = reseau
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_yd_docker_symfony
        restart: always
        depends_on:
            - db
        ports: 
            - 8080:80
        environment:                                # bdd host. Here it's my bdd container
            PMA_HOST: db
        networks:
            - dev

    maildev:
        image: maildev/maildev
        container_name: maildev_yd_docker_symfony
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
            - "8081:80"
        restart: always
        networks:
            - dev

    www:
        build: php
        container_name: www_yd_docker_symfony
        ports:
            - "8741:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - dev

networks:
    dev:

volumes: 
    db-data: